os:
  - osx

language: node_js

cache:
  - yarn
  - $HOME/.electron
  - $HOME/.yarn

node_js:
  - '0.8'

install:
  - brew install yarn
  - yarn

env:
    - TRAVIS_CI=TRAVIS_CI

script:
    - yarn run release
